### ISSUE TITLE
How to remove default padding around the text?

### ISSUE THREAD

**Issue by klemenzagar91** [hsusmita/SwiftResponsiveLabel#1]
Hi, is it possible to remove this default padding that label has around the text?

<img src="https://cloud.githubusercontent.com/assets/5512848/26096548/d3185d40-3a21-11e7-92a6-b5b83dc63ac7.png" width="400">

**Comment by hsusmita** [comment]
@klemenzagar91 You can change the alignment to `left` for the label.

<img width="261" alt="screenshot 2018-10-26 at 1 27 11 pm" src="https://user-images.githubusercontent.com/3590619/47552788-2e612000-d923-11e8-9a9c-79795522db69.png">
